<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.35">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Consumo responsable en Chile.</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="BorradorF_files/libs/clipboard/clipboard.min.js"></script>
<script src="BorradorF_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="BorradorF_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="BorradorF_files/libs/quarto-html/popper.min.js"></script>
<script src="BorradorF_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="BorradorF_files/libs/quarto-html/anchor.min.js"></script>
<link href="BorradorF_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="BorradorF_files/libs/quarto-html/quarto-syntax-highlighting-46f66b053e56abd73bb6e954d61a315b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="BorradorF_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="BorradorF_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="BorradorF_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="BorradorF_files/libs/kePrint-0.0.1/kePrint.js"></script>

<link href="BorradorF_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">

<link href="BorradorF_files/libs/table1-1.0/table1_defaults.css" rel="stylesheet">



</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Consumo responsable en Chile.</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="el-consumo-y-la-construcción-de-la-subjetividad" class="level2">
<h2 class="anchored" data-anchor-id="el-consumo-y-la-construcción-de-la-subjetividad">El Consumo y la Construcción de la Subjetividad</h2>
<p>En la estructura social contemporánea, el consumo ha desplazado al trabajo como la actividad primordial que genera y organiza los vínculos sociales <span class="citation" data-cites="bauman2007">Bauman (<a href="#ref-bauman2007" role="doc-biblioref">2007a</a>)</span> No se trata de un simple medio para satisfacer necesidades básicas, sino de un atributo de una sociedad donde el deseo alienado del individuo es la fuerza motriz que mantiene el sistema en movimiento <span class="citation" data-cites="bauman2007">(<a href="#ref-bauman2007" role="doc-biblioref">Bauman 2007a</a>)</span>; <span class="citation" data-cites="ishopt">(<a href="#ref-ishopt" role="doc-biblioref"><em>I Shop Therefore i Know That i Am</em>, n.d.</a>)</span>. En este contexto, surge el “fetichismo de la subjetividad”, un fenómeno donde la supuesta soberanía del consumidor oculta las relaciones de compraventa detrás de la construcción de la identidad <span class="citation" data-cites="bauman2007a">(<a href="#ref-bauman2007a" role="doc-biblioref">Bauman 2007b</a>)</span>. El individuo se percibe como un sujeto libre que elige entre miles de opciones, pero su identidad se produce y recicla constantemente a través del acto de consumir, convirtiéndolo en un producto deseable capaz de generar demanda en el mercado (<span class="citation" data-cites="bauman2007">(<a href="#ref-bauman2007" role="doc-biblioref">Bauman 2007a</a>)</span>; <span class="citation" data-cites="pulido2007">(<a href="#ref-pulido2007" role="doc-biblioref">Pulido and Colín 2007</a>)</span>).</p>
</section>
<section id="la-particularidad-del-caso-chileno-ciudadanía-crediticia-y-desplazamiento" class="level2">
<h2 class="anchored" data-anchor-id="la-particularidad-del-caso-chileno-ciudadanía-crediticia-y-desplazamiento">La Particularidad del Caso Chileno: Ciudadanía Crediticia y Desplazamiento</h2>
<p>En Chile, esta lógica de la sociedad de consumidores se manifiesta a través de la “estrategia del ideal desplazado” (<span class="citation" data-cites="cristoffanini">(<a href="#ref-cristoffanini" role="doc-biblioref">Cristoffanini, n.d.</a>)</span>; <span class="citation" data-cites="mccracken1986">(<a href="#ref-mccracken1986" role="doc-biblioref">McCracken 1986</a>)</span>). Ante la frustración de no alcanzar un estatus de desarrollo real, los ciudadanos materializan fragmentos de esa modernidad anhelada a través del consumo inmediato. Esta dinámica sostiene una “ciudadanía crediticia”, donde la identidad y el sentido de pertenencia no se miden por la incidencia política, sino por la capacidad de acceso al mercado.</p>
<p>El consumo opera así como un dispositivo de domesticación: el placer inmediato del objeto compensa el disciplinamiento laboral, mientras que el endeudamiento asegura la reproducción del orden social <span class="citation" data-cites="moulian">(<a href="#ref-moulian" role="doc-biblioref">Emparanza, n.d.-a</a>)</span>. Surge la figura del “ciudadano credit-card”, un sujeto cuya existencia social es validada por su solvencia financiera. Sin embargo, al perder su capacidad de pago, este individuo pierde su “ciudadanía real” y queda relegado a la infraclase, perdiendo sus derechos de pertenencia y valor social <span class="citation" data-cites="bauman2007">(<a href="#ref-bauman2007" role="doc-biblioref">Bauman 2007a</a>)</span>. En este escenario, el mercado de bienes y servicios ejerce un poder soberano, dictando sentencias de exclusión inapelables para los “consumidores fallados” <span class="citation" data-cites="bauman2007">(<a href="#ref-bauman2007" role="doc-biblioref">Bauman 2007a</a>)</span>.</p>
</section>
<section id="retailización-y-gubernamentalidad-financiera." class="level2">
<h2 class="anchored" data-anchor-id="retailización-y-gubernamentalidad-financiera.">Retailización y Gubernamentalidad Financiera.</h2>
<p>El modelo neoliberal chileno se ha consolidado mediante la “retailización” del crédito, proceso liderado por grandes tiendas que bancarizaron a los sectores populares <span class="citation" data-cites="marambio-tapia2022">(<a href="#ref-marambio-tapia2022" role="doc-biblioref">Marambio-Tapia 2022a</a>)</span>. Esto no fue solo una democratización del acceso a bienes, sino una mutación hacia una “gubernamentalidad financiera” (González López, 2018). El endeudamiento dejó de ser un estigma para convertirse en una tecnología de integración social y una “extensión permanente” del salario (González López, 2018; <span class="citation" data-cites="marambio-tapia2022">(<a href="#ref-marambio-tapia2022" role="doc-biblioref">Marambio-Tapia 2022a</a>)</span>). Al normalizar la deuda como un componente cotidiano de la economía doméstica, el retail logró desplazar los conflictos distributivos hacia la esfera privada, produciendo sujetos financieros cuya identidad se valida en el engranaje del pago permanente (González López, 2018; Marambio-Tapia, 2011).</p>
</section>
<section id="consumo-crítico-y-responsable-como-contra-agencia" class="level2">
<h2 class="anchored" data-anchor-id="consumo-crítico-y-responsable-como-contra-agencia">Consumo Crítico y Responsable como Contra-agencia</h2>
<p>Frente a la atomización individualista, surge el consumo responsable y el consumo crítico como formas de participación y deliberación política (Ariztía et al., 2009; <span class="citation" data-cites="marambio-tapia2022">(<a href="#ref-marambio-tapia2022" role="doc-biblioref">Marambio-Tapia 2022a</a>)</span>). El consumo responsable se define operativamente como la adaptación de hábitos para reducir impactos negativos en el medio ambiente y la sociedad (Ariztía et al., 2009). Por su parte, el consumo crítico busca “desnaturalizar” el modo normal de consumir, cuestionando imperativos como el endeudamiento sistémico o la obsolescencia programada.</p>
<p>Estas prácticas incorporan una dimensión ética y reflexiva donde el acto de compra se transforma en un ejercicio de ciudadanía política (Ariztía et al., 2009; <span class="citation" data-cites="marambio-tapia2022">(<a href="#ref-marambio-tapia2022" role="doc-biblioref">Marambio-Tapia 2022a</a>)</span>). A través de herramientas de contra-agencia, como el boicot a marcas o la participación en economías alternativas (trueque y cooperativas), los individuos buscan romper estructuras de exclusión y producir comunidad fuera de la lógica del mercado desregulado <span class="citation" data-cites="marambio-tapia2022">(<a href="#ref-marambio-tapia2022" role="doc-biblioref">Marambio-Tapia 2022a</a>)</span>. En este sentido, las mercancías dejan de ser simples objetos de deseo para entenderse como un sistema de información que los individuos utilizan para construir un universo social inteligible y disputar significados públicos <span class="citation" data-cites="douglas1990">(<a href="#ref-douglas1990" role="doc-biblioref">Douglas and Isherwood 1990</a>)</span>.</p>
<p>Con el fin de profundizar en estas dinámicas, el presente documento propone realizar un análisis de cluster por medio del algoritmo K-Prototypes (Fonseca, 2013; <span class="citation" data-cites="szepannek2019a">(<a href="#ref-szepannek2019a" role="doc-biblioref">Szepannek 2019a</a>)</span>). El objetivo es identificar patrones de comportamiento que permitan agrupar a los individuos por su relación con el consumo, el crédito y su potencial de agencia crítica. Este enfoque permitirá diferenciar a los sujetos que operan bajo una lógica de integración pasiva de aquellos que utilizan el consumo como una herramienta de subjetivación política y social.</p>
</section>
<section id="variables." class="level1">
<h1>Variables.</h1>
<p>Se realizo un analisis factorial exploratorio a partir de las baterias O1, O2, O3 y O4 con el fin de reducir la dimenisonalidad e identificar las variables latentes que explican las respuestas a los items.</p>
<p>A partir de el modelo de medida resultante se construyeron cuatro indices referentes a las dimensiones del consumo; Consumo critico, Eficiencia domenstica, Planificacion, Facilidad de reciclaje y percepcion de responsabilidad mediante el metodo de regresion.</p>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'kableExtra'</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>The following object is masked from 'package:dplyr':

    group_rows</code></pre>
</div>
<div class="cell-output-display">
<table class="table table-striped table-hover table-condensed caption-top table-sm small">
<caption>Análisis Factorial: Cargas de los Ítems</caption>
<colgroup>
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th" style="text-align: left; empty-cells: hide; border-bottom: hidden;"></th>
<th colspan="5" data-quarto-table-cell-role="th" style="text-align: center; border-bottom: hidden; padding-bottom: 0; padding-left: 3px; padding-right: 3px;"><div style="border-bottom: 1px solid #ddd; padding-bottom: 5px; ">
Factores Extraídos
</div></th>
</tr>
<tr class="even">
<th style="text-align: left;" data-quarto-table-cell-role="th">Variable</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Consumo Crítico</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Eficiencia Hogar</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Planificación</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Facilidad Reciclaje</th>
<th style="text-align: center;" data-quarto-table-cell-role="th">Percepción Resp.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O3_1</td>
<td style="text-align: center;">0.772</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O3_4</td>
<td style="text-align: center;">0.786</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O2_11</td>
<td style="text-align: center;">0.643</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O3_2</td>
<td style="text-align: center;">0.428</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O3_3</td>
<td style="text-align: center;">0.535</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O3_7</td>
<td style="text-align: center;">0.665</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O2_1</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.665</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O2_2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.601</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O2_3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.605</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O2_5</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.638</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O2_4</td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.573</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O1_10</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.650</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O2_8</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.774</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O2_9</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.577</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O4_2</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.440</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O4_3</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.877</td>
<td style="text-align: center;"></td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O4_5</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.780</td>
<td style="text-align: center;"></td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O4_1</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.613</td>
</tr>
<tr class="odd">
<td style="text-align: left; font-weight: bold;">O4_8</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.588</td>
</tr>
<tr class="even">
<td style="text-align: left; font-weight: bold;">O4_12</td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;"></td>
<td style="text-align: center;">0.441</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Por otra parte, se construyo la variable “situacion financiera” a partir de la resta de la variable ingresos con la suma de los gastos reportados, a modo de poder identificar si el individuo posee mas gastos de sus ingresos.</p>
<p>Tambien se utilizaron las variables m15 “situacion de endeudamiento”, m9 “posicion politica”, M13_1 “Tarjetas de tiendas o Supermercados”, M13_3 “Credito de consumo”, M13_7 “tarjeta de credito bancaria”.</p>
</section>
<section id="descriptivos" class="level1">
<h1>Descriptivos</h1>
<div class="cell">
<div class="cell-output-display">
<div class="Rtable1">
<table class="Rtable1 caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th class="rowlabel firstrow lastrow" data-quarto-table-cell-role="th"></th>
<th class="firstrow lastrow" data-quarto-table-cell-role="th"><span class="stratlabel">Overall<br>
<span class="stratn">(N=1623)</span></span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td class="rowlabel firstrow"><span class="varlabel">factor(situacion_financiera.x)</span></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Déficit (Gasta más)</td>
<td>523 (32.2%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">No Déficit (Ahorro/Equilibrio)</td>
<td>927 (57.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Sin datos</td>
<td class="lastrow">173 (10.7%)</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow"><span class="varlabel">factor(M15)</span></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">1</td>
<td>545 (33.6%)</td>
</tr>
<tr class="odd">
<td class="rowlabel">2</td>
<td>349 (21.5%)</td>
</tr>
<tr class="even">
<td class="rowlabel">3</td>
<td>241 (14.8%)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">4</td>
<td class="lastrow">488 (30.1%)</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow"><span class="varlabel">Consumo_Critico</span></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>-0.00164 (0.695)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">0.0182 [-1.98, 2.29]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow"><span class="varlabel">Eficiencia_Hogar</span></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>-0.0107 (0.556)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">0.00584 [-2.29, 1.39]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow"><span class="varlabel">Planificacion</span></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>-0.00640 (0.546)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">-0.00475 [-1.94, 1.48]</td>
</tr>
<tr class="odd">
<td class="rowlabel firstrow"><span class="varlabel">Facilidad_reciclaje</span></td>
<td class="firstrow"></td>
</tr>
<tr class="even">
<td class="rowlabel">Mean (SD)</td>
<td>0.00626 (0.379)</td>
</tr>
<tr class="odd">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">-0.00398 [-0.783, 1.00]</td>
</tr>
<tr class="even">
<td class="rowlabel firstrow"><span class="varlabel">Percep_responsabilidad</span></td>
<td class="firstrow"></td>
</tr>
<tr class="odd">
<td class="rowlabel">Mean (SD)</td>
<td>-0.00274 (0.456)</td>
</tr>
<tr class="even">
<td class="rowlabel lastrow">Median [Min, Max]</td>
<td class="lastrow">-0.0126 [-1.52, 1.28]</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>El análisis contempla una muestra de 1,623 sujetos. Las variables continuas, al ser puntuaciones factoriales estimadas mediante el método de regresión, se presentan de forma estandarizada (M≈0). Esto convierte al “sujeto promedio” en el eje central de referencia, donde los valores positivos o negativos indican la posición relativa del individuo respecto a la norma del grupo y no la ausencia de la conducta.</p>
<p>En este marco, el factor de Consumo Crítico destaca por ser el más disperso (σ=0.70), presentando el rango de respuesta más amplio de todo el estudio (de -2.0 a 2.3). Esta alta variabilidad permite identificar grupos polares: una vanguardia de sujetos con un compromiso ético excepcional que alcanzan los puntajes máximos de la muestra y, de manera simétrica, un grupo en el extremo opuesto con una desconexión total de estas prácticas.</p>
<p>En contraste, las dimensiones de Eficiencia en el Hogar (σ=0.56), Planificación (σ=0.55) y Facilidad de Reciclaje (σ=0.38) muestran una notable homogeneidad. La Facilidad de Reciclaje es la variable con mayor consenso, lo que sugiere que las barreras o condiciones para reciclar son percibidas de manera casi idéntica por todo el espectro de encuestados. Mientras que la Planificación sigue una distribución equilibrada, la Eficiencia Doméstica presenta una asimetría hacia los valores negativos (mínimo de -2.3), indicando que existe una “cola” de sujetos con niveles de ahorro energético y de agua particularmente bajos que se alejan del promedio más que los sujetos eficientes.</p>
<p>Por otro lado, la Percepción de Responsabilidad (σ=0.46) refuerza esta tendencia hacia la cohesión, concentrando las opiniones sobre la autoría de las consecuencias del consumo cerca de la media. Este equilibrio estadístico en las actitudes contrasta con la realidad material de los hogares. Al observar las motivaciones de compra, la suma de las categorías “Darme un gusto a mí mismo” y “Darle un gusto a mi familia” valida la tesis de la “domesticación” del consumo en Chile: el gasto actúa como una herramienta de bienestar privado y cohesión afectiva, posicionando a la familia como la principal unidad de seguridad ante un entorno externo incierto.</p>
<p>Finalmente, se da cuenta de situacion financiera frágil. Los datos indican un deterioro del balance económico: un 33.6% de los sujetos en la variable (M15) declara un aumento en su nivel de endeudamiento, superando a quienes lograron reducir su carga crediticia (21.5%). Esta vulnerabilidad se confirma al observar que un 32.2% de la muestra reporta un déficit financiero (gasta más de lo que gana). En conjunto, los resultados dibujan un perfil de consumidor que, aunque mantiene hábitos de planificación y eficiencia similares a sus pares, se refugia en el consumo familiar como mecanismo de gratificación mientras enfrenta un saldo negativo en su salud financiera general.</p>
<section id="analisis-de-cluster" class="level2">
<h2 class="anchored" data-anchor-id="analisis-de-cluster">Analisis de Cluster</h2>
<p>El proceso se ejecutó mediante el lenguaje R, utilizando la librería clustMixType. <span class="citation" data-cites="szepannek2019">(<a href="#ref-szepannek2019" role="doc-biblioref">Szepannek 2019b</a>)</span> Para determinar la estructura óptima de la partición, se empleó el método del codo (Elbow Method), analizando la evolución de la disimilitud total para un rango de k entre 2 y 10. Tras la inspección de la curva de costos, se seleccionó una solución de 6 clusters, la cual ofrece el mejor equilibrio entre la parsimonia del modelo y la homogeneidad interna de los grupos.</p>
<p>Un aspecto crítico del procedimiento fue la estimación del parámetro λ (lambda), el cual pondera la influencia de las variables categóricas frente a las numéricas en el cálculo de la disimilitud. En este modelo, λ se estableció automáticamente en 3.52, equilibrando el peso de las dimensiones actitudinales (factores) con las condiciones de deuda y balance financiero.</p>
</section>
<section id="grupos" class="level2">
<h2 class="anchored" data-anchor-id="grupos">Grupos</h2>
<p>1 El primer grupo, denominado <em>El Ciudadano Credit-Card de Centro</em> (n=221), es el que presenta el mayor nivel de bancarización. Un 86.4% de sus miembros posee tarjetas de tienda y un 82.3% tiene tarjetas bancarias, lo que lo convierte en el grupo con mayor acceso al crédito. Además, el 66% de los individuos en este grupo utiliza créditos de consumo. Este clúster se ubica en el centro político, con una media en la variable política de 4.88. Muestra actitudes moderadamente positivas hacia el consumo crítico y la planificación, pero un 47% de sus miembros se sienten más endeudados que hace tres años. Esto refleja una integración plena al sistema financiero, aunque con algunos riesgos asociados al endeudamiento constante.</p>
<p>2 El segundo clúster, <em>El Consumidor Crítico de Izquierda</em> (n=226), se caracteriza por su orientación política marcada a la izquierda, con una media de 1.93 en la variable política. Este grupo tiene el uso de crédito más limitado: solo el 27% utiliza tarjetas de retail y un 11% hace uso de créditos de consumo. Este grupo destaca por sus altos niveles de consumo crítico, con una puntuación de 0.21 en esta variable. Un 35.8% de sus miembros declara no tener deudas actuales ni pasadas. El consumo, para este grupo, se utiliza como una herramienta de resistencia política, rechazando la domesticación a través del endeudamiento.</p>
<p>3 En el tercer grupo, denominado <em>El Consumidor Irreflexivo en Riesgo</em> (n=390), se encuentran individuos con los índices más bajos en consumo crítico (-0.46), eficiencia del hogar (-0.48) y planificación (-0.43). Políticamente, este grupo se sitúa en el centro, con una media de 4.88 en la variable política. Aunque el 77% no utiliza tarjetas de retail, este grupo tiene el mayor déficit financiero, con un 36.4% de sus miembros reportando dificultades económicas. Este grupo se clasifica como “consumidor fallado”, pues sus recursos no están a la altura de las exigencias del sistema, lo que los coloca en una posición de vulnerabilidad.</p>
<p>4 Por otro lado, <em>El Consumidor Apático de Derecha</em> (n=140) tiene una orientación política hacia la derecha, con una media de 8.36 en la variable política. Este grupo muestra un fuerte desinterés por las prácticas de consumo responsable, con puntuaciones muy negativas en consumo crítico (-0.55) y eficiencia (-0.56). El 30.7% de sus miembros posee tarjetas de retail, pero, a pesar de su apatía ética hacia el consumo, un 54% reporta no tener déficit financiero, lo que contrasta con la falta de implicación ética en sus decisiones de consumo.</p>
<p>5 El quinto clúster, <em>El Ciudadano Consciente de Derecha</em> (n=188), posee una orientación política de derecha marcada (M9 media: 9.33). Este grupo es notable por sus altos niveles de eficiencia en el hogar (0.31) y planificación (0.27). A pesar de su postura política, los miembros de este clúster destacan por su alta solvencia financiera, con un 58% sin déficit. Su consumo crítico no surge de una resistencia al sistema, sino de un estilo de vida sustentable y asociado a una distinción social que es posible gracias a su poder adquisitivo.</p>
<p>6 Finalmente, el <em>Planificador de Centro-Derecha</em> (n=458) es el clúster más numeroso y se sitúa en el centro-derecha (M9 media: 5.13). Este grupo destaca por sus altos niveles de planificación (0.29) y eficiencia hogareña (0.31). El 48.9% de los miembros de este clúster declara no tener deudas (M15=4). Este grupo representa a la clase media que ha logrado “domesticar” el crédito, incorporándolo de manera funcional a su rutina diaria sin caer en el sobreendeudamiento.</p>
<p>En conjunto, estos clústers proporcionan una visión detallada de cómo diferentes grupos sociales manejan el consumo, el crédito y la planificación financiera, reflejando la complejidad de las dinámicas socioeconómicas presentes en la población.</p>
<p>Algunos grupos evidencian una suerte de dicotomía entre Ciudadano y Consumidor; la segmentación muestra que la identidad en Chile pareciera no construirse de manera homogenea. Mientras el Clúster 2 ejerce una “ciudadanía política” tradicional desde la izquierda, rechazando el crédito como dispositivo de control <span class="citation" data-cites="emparanza">(<a href="#ref-emparanza" role="doc-biblioref">Emparanza, n.d.-b</a>)</span>, el Clúster 1 personifica la “ciudadanía crediticia”, donde la integración social depende de la solvencia financiera y el acceso al mercado. El hecho de que solo la mitad de los chilenos se defina antes como ciudadano que como consumidor refuerza la idea de una erosión de los relatos colectivos frente al “yo consumidor”.</p>
<p>Tambien se identifica la “Retailización” y la Normalización de la Deuda. Tanto el clúster 6 como el clúster 1 evidencian la “retailización” del crédito liderado por grandes tiendas <span class="citation" data-cites="marambio-tapia2022a">(<a href="#ref-marambio-tapia2022a" role="doc-biblioref">Marambio-Tapia 2022b</a>)</span>. Para el clúster 6, la deuda no es un fracaso, sino una herramienta de agencia para gestionar la cotidianeidad y mantener estándares de vida. Esto refuerza aquella idea de que el endeudamiento se ha convertido en una “gubernamentalidad financiera” que permite a los sectores medios y bajos materializar fragmentos de modernidad en el presente <span class="citation" data-cites="gonzálezlópez2018a">(<a href="#ref-gonzálezlópez2018a" role="doc-biblioref">González López 2018</a>)</span>.</p>
<p>En cuanto al consumo Crítico, se evidencian diferenciadamente dos elementos; Resistencia y Estatus. Pareciera existir una tensión entre el Clúster 2 y el Clúster 5. En el primero, el consumo crítico parece una herramienta de “contra-agencia” política. En el segundo, los altos índices de consumo responsable en sectores de derecha sugieren que estas prácticas pueden ser también una forma de distinción estética y moral ligada al alto capital cultural y económico <span class="citation" data-cites="pulido2007">(<a href="#ref-pulido2007" role="doc-biblioref">Pulido and Colín 2007</a>)</span>. Esto coincide con lo planteado por Ariztía et al.&nbsp;(2009), donde el “consumidor consciente” es en ocaciones un segmento mínimo con alto poder adquisitivo.</p>
<p>4. Los “Consumidores Fallados”: El Clúster 3, con sus índices negativos de planificación y su alto déficit economico, representa lo que <span class="citation" data-cites="bauman2007">Bauman (<a href="#ref-bauman2007" role="doc-biblioref">2007a</a>)</span> denomina “consumidores fallados”. Al carecer de la competencia consumista exigida por el sistema, estos sujetos no son vistos como personas con necesidades sociales, sino como individuos con “falencias personales”, quedando expuestos a una exclusión inapelable del mercado soberano.</p>
<p>Esta segmentación de los consumidores en Chile revela una dicotomía entre el “ciudadano” y el “consumidor”, que se refleja en algunos de los distintos clústers identificados en el análisis. El Clúster 2, denominado como <em>El Consumidor Crítico de Izquierda</em>, ejerce una forma de “ciudadanía política” tradicional desde la izquierda, rechazando el crédito como un mecanismo de control social. Este grupo ve podria ver al crédito como una herramienta que limita la libertad, optando por mantenerse al margen de dicho sistema financiero. En contraste, el Clúster 1, <em>El Ciudadano Credit-Card de Centro</em>, representa aquella “ciudadanía crediticia”, donde la integración social y la participación en la vida económica están profundamente vinculadas con la solvencia financiera y el acceso a bienes. Este fenómeno refleja una creciente dependencia del mercado y de las instituciones financieras para la construcción de la identidad, lo que refuerza la idea de que, en Chile, solo la mitad de la población se define principalmente como “ciudadano”, mientras que la otra mitad lo hace como “consumidor”. Esto apunta a una erosión de los relatos colectivos, donde el “yo consumidor” ha ido ganando terreno frente al concepto tradicional de ciudadanía.</p>
<p>La segmentación también pone en evidencia la “retailización” del crédito, especialmente en los clústers 1 y 6. La “retailización” hace referencia al proceso mediante el cual las grandes tiendas y cadenas de retail se convierten en actores clave en la distribución y acceso al crédito, normalizando la deuda como una herramienta cotidiana. El Clúster 6, <em>El Planificador de Centro-Derecha</em>, evidencia cómo la deuda no se percibe como un fracaso económico, sino como una herramienta estratégica para gestionar la vida cotidiana y mantener ciertos estándares de consumo. Este fenómeno confirma lo planteado por González López (2018), quien argumenta que el endeudamiento se ha transformado en una “gubernamentalidad financiera”, donde los sectores medios y bajos utilizan el crédito como un medio para acceder a los fragmentos de modernidad, es decir, para vivir en un contexto de consumo que antes solo estaba al alcance de los sectores más altos.</p>
<p>La relación entre consumo crítico y estatus es otro aspecto que genera una interesante tensión entre el Clúster 2 y el Clúster 5. El consumo crítico, para el Clúster 2, parece ser una herramienta de “contra-agencia” política, un rechazo al consumo tradicional y a la integración en el sistema financiero. En cambio, para el Clúster 5, <em>El Ciudadano Consciente de Derecha</em>, el consumo responsable no solo tiene connotaciones políticas, sino que también se presenta como una forma de distinción estética y moral. Este grupo, que se sitúa en el sector de derecha, practica un consumo ético que está vinculado al alto capital cultural y económico, y que tiene como objetivo diferenciarse de otros sectores. Esto coincide con lo planteado por Ariztía et al.&nbsp;(2009), donde el “consumidor consciente” es descrito como un segmento reducido pero con alto poder adquisitivo, que utiliza el consumo responsable como una forma de afirmar su estatus social y cultural.</p>
<p>Finalmente, el Clúster 3, <em>El Consumidor Irreflexivo en Riesgo</em>, representa lo que <span class="citation" data-cites="bauman2007">Bauman (<a href="#ref-bauman2007" role="doc-biblioref">2007a</a>)</span> denomina “consumidores fallados”. Este grupo tiene índices negativos de planificación y altos niveles de déficit económico, lo que refleja una falta de competencia en las prácticas consumistas exigidas por el sistema. A pesar de no ser considerados personas con necesidades sociales, estos individuos son vistos como responsables de sus propias falencias personales, quedando excluidos del mercado soberano. La falta de recursos y la incapacidad para adaptarse a las demandas del sistema los convierte en sujetos vulnerables, condenados a una exclusión económica inapelable. La caracterización de este grupo refuerza la idea de que aquellos que no cumplen con las exigencias del mercado son rápidamente marginados y excluidos de las oportunidades de consumo que el sistema ofrece.</p>

</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" role="list">
<div id="ref-bauman2007" class="csl-entry" role="listitem">
Bauman, Zygmunt. 2007a. <em>Consuming Life</em>. Polity.
</div>
<div id="ref-bauman2007a" class="csl-entry" role="listitem">
Bauman, Zygmunt. 2007b. <em>Consuming Life</em>. Polity.
</div>
<div id="ref-cristoffanini" class="csl-entry" role="listitem">
Cristoffanini, Pablo. n.d. <em>La Utopía Consumista En Chile</em>.
</div>
<div id="ref-douglas1990" class="csl-entry" role="listitem">
Douglas, Mary, and Baron C. Isherwood. 1990. <em>El mundo de los bienes: hacia una antropología de consumo</em>. Noventa 22. Grijalbo Consejo Nacional para la Cultura y las Artes.
</div>
<div id="ref-moulian" class="csl-entry" role="listitem">
Emparanza, Tomás Moulian. n.d.-a. <em>Chile actual: anatomía de un mito</em>.
</div>
<div id="ref-emparanza" class="csl-entry" role="listitem">
Emparanza, Tomás Moulian. n.d.-b. <em>Chile actual: anatomía de un mito</em>.
</div>
<div id="ref-gonzálezlópez2018a" class="csl-entry" role="listitem">
González López, Felipe. 2018. <span>“Crédito, deuda y gubernamentalidad financiera en Chile.”</span> <em>Revista mexicana de sociología</em> 80 (4): 881–908. <a href="http://www.scielo.org.mx/scielo.php?script=sci_abstract&amp;pid=S0188-25032018000400881&amp;lng=es&amp;nrm=iso&amp;tlng=es">http://www.scielo.org.mx/scielo.php?script=sci_abstract&amp;pid=S0188-25032018000400881&amp;lng=es&amp;nrm=iso&amp;tlng=es</a>.
</div>
<div id="ref-ishopt" class="csl-entry" role="listitem">
<em>I Shop Therefore i Know That i Am: The Metaphysical Basis of Modern Consumerism</em>. n.d. <a href="https://doi.org/10.4324/9781003085232-4">https://doi.org/10.4324/9781003085232-4</a>.
</div>
<div id="ref-marambio-tapia2022" class="csl-entry" role="listitem">
Marambio-Tapia, Alejandro. 2022a. <span>“Normalización de la Deuda y Retailización del Crédito como Pilares del Neoliberalismo Chileno Avanzado.”</span> <em>Iberoamericana <span></span> Nordic Journal of Latin American and Caribbean Studies</em> 51 (1): 14–25. <a href="https://doi.org/10.16993/iberoamericana.529">https://doi.org/10.16993/iberoamericana.529</a>.
</div>
<div id="ref-marambio-tapia2022a" class="csl-entry" role="listitem">
Marambio-Tapia, Alejandro. 2022b. <span>“Normalización de la Deuda y Retailización del Crédito como Pilares del Neoliberalismo Chileno Avanzado.”</span> <em>Iberoamericana <span></span> Nordic Journal of Latin American and Caribbean Studies</em> 51 (1): 14–25. <a href="https://doi.org/10.16993/iberoamericana.529">https://doi.org/10.16993/iberoamericana.529</a>.
</div>
<div id="ref-mccracken1986" class="csl-entry" role="listitem">
McCracken, Grant. 1986. <span>“Culture and Consumption: A Theoretical Account of the Structure and Movement of the Cultural Meaning of Consumer Goods.”</span> <em>Journal of Consumer Research</em>, ahead of print. <a href="https://doi.org/10.1086/209048">https://doi.org/10.1086/209048</a>.
</div>
<div id="ref-pulido2007" class="csl-entry" role="listitem">
Pulido, Gabriela M. Lara, and Georgina Colín. 2007. <span>“Reseña de <span>"</span>Sociedad de Consumo y Cultura Consumista<span>"</span> de Zygmunt Bauman.”</span> <em>Argumentos</em> 20 (55): 211–16. <a href="https://www.redalyc.org/articulo.oa?id=59505508">https://www.redalyc.org/articulo.oa?id=59505508</a>.
</div>
<div id="ref-szepannek2019" class="csl-entry" role="listitem">
Szepannek, Gero. 2019b. <span>“clustMixType: User-Friendly Clustering of Mixed-Type Data in r.”</span> <em>The R Journal</em> 10 (2): 200. <a href="https://doi.org/10.32614/RJ-2018-048">https://doi.org/10.32614/RJ-2018-048</a>.
</div>
<div id="ref-szepannek2019a" class="csl-entry" role="listitem">
Szepannek, Gero. 2019a. <span>“clustMixType: User-Friendly Clustering of Mixed-Type Data in r.”</span> <em>The R Journal</em> 10 (2): 200. <a href="https://doi.org/10.32614/RJ-2018-048">https://doi.org/10.32614/RJ-2018-048</a>.
</div>
</div></section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>