---
title: "Analisis"
format: html
editor: visual
---

## Analisis

```{r}
library(tidyverse)
library(haven)
library(sjPlot)
library(summarytools)
library(psych)
library(lavaan)
Encuesta_Sociedad_de_Consumo_2023 <- read_sav("Encuesta Sociedad de Consumo 2023.sav")
View(Encuesta_Sociedad_de_Consumo_2023)
datos<- Encuesta_Sociedad_de_Consumo_2023 %>% select(SEXO, EDAD, EDADR, NSE, NSE_RECOD, NSE_sint, ZONA, B1, C1, C2, C3_1:C3_16, C5a, A1:`A2#4`, O1_1:O1_10, O2_1:O2_14 , O3_1:O3_10, O4_1:O4_12, O5, E2, E3, E4, `S5#2`:`S5#99`, `T6#1`:`T6#99`, M14, M5, M6, M7, M8, M9, M10, M11_1:M11_8, M12_1:M12_6, `M13#1`:`M13#99`, M14, M15, M16_1:M16_9, M18_1:M18_7)

```

```{r subset modulo C}

modulo_C <- datos %>%
  select(C3_1:C3_16)
```

MODULO C

```{r EFA Modulo c}

polichoric_c <- polychoric(modulo_C)

fa.parallel(polichoric_c$rho, fa = "fa", n.iter = 100, cor = "poly", n.obs = 1623) #segun la regla de Kaiser, aqui corresponderia un uninco factor, aun que podrian ser 2. Por el criterio del nunmero de factores, podrian ser dos por principio de parsimonia.

fa(r = polichoric_c$rho, nfactors = 3, rotate = "oblimin")
#Tanto las tres soluciones dan soluciones con cargas factoriales bajas. Los item de la bateria sugieren independencia entre si. Sugeriria no hacer escalas.
```

MODULO O1

```{r subset bateria o1 }
modulo_o1 <- datos %>% select(O1_1:O1_10)
modulo_o1 <- modulo_o1 %>%
  mutate(across(everything()), as.numeric)

polichoric_o1 <- polychoric(modulo_o1)

fa.parallel(
  polichoric_o1$rho,
  fa = "fa",           # Usas Análisis Factorial (FA)
  n.iter = 100,
  n.obs = 1623,
  # Asegúrate de que el argumento 'plot' esté en TRUE (suele ser el default)
  plot = TRUE
)
efa <- fa(r = polichoric_o1$rho, nfactors = 2, rotate = "oblimin")
print(efa, cut = 0.3, sort = TRUE, digits = 2)
#el efa suguiere una estructura de dos factores.


#Hacemos el confirmatorio ahora
cfa_o1 <-'factor1 =~ O1_1 + O1_2 + O1_3 + O1_4
factor2 =~ O1_5 + O1_6 + O1_7 + O1_4 +O1_1
factor1 ~~ factor2
'

fit<- cfa(
  model = cfa_o1,
  data = modulo_o1,
  estimator = "WLSMV",
  ordered = TRUE,
  missing = "pairwise"
)

summary(fit, fit.measures = TRUE)
summary(fit, standardized = TRUE)

modindices(fit)

```

MODULO O COMPLETO.

```{r}
moduloc <- datos %>% select(starts_with("O"))
moduloc <- moduloc %>% select(-O5)


```
